# Generated by Django 4.0.4 on 2022-05-29 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenders',
            name='bidder',
        ),
        migrations.CreateModel(
            name='Bidders_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bidder')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenders')),
            ],
        ),
    ]
