# Generated by Django 4.0.4 on 2022-05-29 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tenders_bidder_bidders_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mydeals_List_tenderer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenders')),
                ('tenderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenderer')),
            ],
        ),
        migrations.RenameModel(
            old_name='Bidders_List',
            new_name='Mydeals_List_bidder',
        ),
        migrations.AddField(
            model_name='bid',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Mydeals_List',
        ),
    ]
