# Generated by Django 4.0.4 on 2022-06-04 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_mydeals_list_tenderer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bidder',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tenderer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tenderer',
            name='password',
        ),
        migrations.AddField(
            model_name='bidder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenderer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bidder',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tenderer',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='pdf_tender',
            field=models.FileField(null=True, upload_to='pdf_tender/'),
        ),
    ]
