# Generated by Django 4.0.4 on 2022-06-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_bidder_email_remove_bidder_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='insurance_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bidder',
            name='terms_of_ref_price',
            field=models.IntegerField(default=0),
        ),
    ]
