# Generated by Django 4.0.4 on 2022-06-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bidder_insurance_money_bidder_terms_of_ref_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder',
            name='insurance_money',
        ),
        migrations.RemoveField(
            model_name='bidder',
            name='terms_of_ref_price',
        ),
        migrations.AddField(
            model_name='tenders',
            name='insurance_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenders',
            name='terms_of_ref_price',
            field=models.IntegerField(default=0),
        ),
    ]
