# Generated by Django 4.0.4 on 2022-06-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_tenders_endate_alter_tenders_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenders',
            name='insurance_money',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='terms_of_ref_price',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
