# Generated by Django 4.0.4 on 2022-06-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_bid_bidder_remove_bid_tender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bidder',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenderer',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenderer',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
